version: 2
updates:

  # 1. Go module updates
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(go)"
    labels:
      - "dependencies"
      - "release-note-none"
    ignore:
      - dependency-name: "sigs.k8s.io/gateway-api-inference-extension"
    groups:
      go-dependencies:
        patterns:
          - "*"
      kubernetes:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"

  # 2. GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "release-note-none"
    commit-message:
      prefix: "deps(actions)"

  # 3. Docker base image updates (e.g., for Dockerfile FROM lines)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps(docker)"
