apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${MODEL_NAME_SAFE}-vllm-sim
  labels:
    app: ${POOL_NAME}
spec:
  replicas: ${VLLM_REPLICA_COUNT}
  selector:
    matchLabels:
      app: ${POOL_NAME}
  template:
    metadata:
      labels:
        app: ${POOL_NAME}
    spec:
      containers:
      - name: vllm
        image: ghcr.io/llm-d/llm-d-inference-sim:latest
        imagePullPolicy: IfNotPresent
        args:
        - "--port=8000"
        - "--model=${MODEL_NAME}"
        - "--enable-kvcache=${KV_CACHE_ENABLED}"
        - "--kv-cache-size=1024"
        - "--block-size=16"
        - "--zmq-endpoint=tcp://${EPP_NAME}.default.svc.cluster.local:5557"
        - "--event-batch-size=16"
        - "--tokenizers-cache-dir=/tokenizer-cache"
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: PORT
          value: "8000"
        - name: PYTHONHASHSEED
          value: "42"
        volumeMounts:
        - name: tokenizer-cache
          mountPath: /tokenizer-cache
      volumes:
      - name: tokenizer-cache
        emptyDir: {}

