apiVersion: v1
kind: Service
metadata:
  name: ${EPP_NAME}
spec:
  selector:
    app: ${EPP_NAME}
  ports:
  - name: default
    protocol: TCP
    port: 9002
    targetPort: 9002
    appProtocol: http2
  - name: zmq
    protocol: TCP
    port: 5557
    targetPort: 5557
    appProtocol: tcp
  type: ClusterIP
