name: Check Typos

on:
  pull_request:
  push:

jobs:
  typos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check typos
        uses: crate-ci/typos@v1.35.7

