name: CI - PR Checks

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        
      - name: Sanity check repo contents
        run: ls -la

      - name: Extract Go version from go.mod
        run: sed -En 's/^go (.*)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV

      - name: Set up Go with cache
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache-dependency-path: ./go.sum

      - name: Install libzmq dependencies (kvcache/kvevents)
        run: |
          sudo apt-get update
          sudo apt-get install -y libzmq3-dev pkg-config

      - name: Set PKG_CONFIG_PATH
        run: echo "PKG_CONFIG_PATH=/usr/lib/pkgconfig" >> $GITHUB_ENV

      - name: go mod tidy
        run: go mod tidy

      - name: Run lint checks
        uses: golangci/golangci-lint-action@v8
        with:
          version: 'v2.1.6'
          args: "--config=./.golangci.yml"

      - name: Run make test
        shell: bash 
        run: |
          make test

      - name: Run make build
        shell: bash
        run: |
          make build
